apiVersion: batch/v1
kind: Job
metadata:
  name: gql-server-seeds
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: migrations
        image: gcr.io/chord-club/gql-server:r2020-14-05.r01
        command: ["node", "commands/extensions.js"]
        env:
          - name: SECRET_PATH
            value: "/data/secrets.json"
        volumeMounts:
          - mountPath: /data
            name: secrets
            readOnly: true
      restartPolicy: Never
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: prd-chordclub-secrets--v003
