version: '3'

services:
  postgres:
    image: postgres:11-alpine
    volumes:
    - './postgres-data:/var/lib/postgresql/data'
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=developer
    - POSTGRES_DB=db
    - POSTGRES_PASSWORD=notsecret
    - PGSSLMODE=disable

  gql-server:
    build: .
    image: chordclub:latest
    volumes:
    - './tmp/secrets.dev.json:/data/secrets.json'
    - './tmp/chord-club-bc4acc7a1282.json:/data/chord-club-bc4acc7a1282.json'
    ports:
    - "4000:4000"
    environment:
    - PGHOST=postgres
    - SECRET_PATH=/data/secrets.json
