version: '3'

services:
  postgres:
    image: postgres:11-alpine
    volumes:
    - './postgres-data:/var/lib/postgresql/data'
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=developer
    - POSTGRES_DB=db
    - POSTGRES_PASSWORD=notsecret
    - PGSSLMODE=disable
